#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Category {
    // Main Categories
    AudioVideo,
    Audio,
    Video,
    Development,
    Education,
    Game,
    Graphics,
    Network,
    Office,
    Settings,
    Utility,

    // Development
    Building,
    Debugger,
    IDE,
    GUIDesigner,
    Profiling,
    RevisionControl,
    Translation,

    // Office
    Calendar,
    ContactManagement,
    Database,
    Dictionary,
    Chart,
    Email,
    Finance,
    FlowChart,
    PDA,
    ProjectManagement,
    Presentation,
    Spreadsheet,
    WordProcessor,

    // Graphics
    Graphics2D,
    VectorGraphics,
    RasterGraphics,
    Graphics3D,
    Scanning,
    OCR,
    Photography,
    Publishing,
    Viewer,

    // Utility
    TextTools,
    DesktopSettings,
    HardwareSettings,
    Printing,
    PackageManager,

    // Network
    Dialup,
    InstantMessaging,
    Chat,
    IRCClient,
    FileTransfer,
    HamRadio,
    News,
    P2P,
    RemoteAccess,
    Telephony,
    TelephonyTools,
    VideoConference,
    WebBrowser,
    WebDevelopment,

    // AudioVideo
    Midi,
    Mixer,
    Sequencer,
    Tuner,
    TV,
    AudioVideoEditing,
    Player,
    Recorder,
    DiscBurning,

    // Game
    ActionGame,
    AdventureGame,
    ArcadeGame,
    BoardGame,
    BlocksGame,
    CardGame,
    KidsGame,
    LogicGame,
    RolePlaying,
    Simulation,
    SportsGame,
    StrategyGame,

    // Education
    Art,
    Construction,
    Music,
    Languages,
    Science,
    ArtificialIntelligence,
    Astronomy,
    Biology,
    Chemistry,
    ComputerScience,
    DataVisualization,
    Economy,
    Electricity,
    Geography,
    Geology,
    Geoscience,
    History,
    ImageProcessing,
    Literature,
    Math,
    NumericalAnalysis,
    MedicalSoftware,
    Physics,
    Robotics,
    Sports,
    ParallelComputing,

    // Other
    Amusement,
    Archiving,
    Compression,
    Electronics,
    Emulator,
    Engineering,
    FileTools,
    FileManager,
    TerminalEmulator,
    Filesystem,
    Monitor,
    Security,
    Accessibility,
    Calculator,
    Clock,
    TextEditor,
    Documentation,

    // Technical
    Core,
    KDE,
    GNOME,
    GTK,
    Qt,
    Motif,
    Java,
    ConsoleOnly,

    // Additional
    Screensaver,
    TrayIcon,
    Applet,
    Shell,
}

impl Category {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "AudioVideo" => Some(Self::AudioVideo),
            "Audio" => Some(Self::Audio),
            "Video" => Some(Self::Video),
            "Development" => Some(Self::Development),
            "Education" => Some(Self::Education),
            "Game" => Some(Self::Game),
            "Graphics" => Some(Self::Graphics),
            "Network" => Some(Self::Network),
            "Office" => Some(Self::Office),
            "Settings" => Some(Self::Settings),
            "Utility" => Some(Self::Utility),
            "Building" => Some(Self::Building),
            "Debugger" => Some(Self::Debugger),
            "IDE" => Some(Self::IDE),
            "GUIDesigner" => Some(Self::GUIDesigner),
            "Profiling" => Some(Self::Profiling),
            "RevisionControl" => Some(Self::RevisionControl),
            "Translation" => Some(Self::Translation),
            "Calendar" => Some(Self::Calendar),
            "ContactManagement" => Some(Self::ContactManagement),
            "Database" => Some(Self::Database),
            "Dictionary" => Some(Self::Dictionary),
            "Chart" => Some(Self::Chart),
            "Email" => Some(Self::Email),
            "Finance" => Some(Self::Finance),
            "FlowChart" => Some(Self::FlowChart),
            "PDA" => Some(Self::PDA),
            "ProjectManagement" => Some(Self::ProjectManagement),
            "Presentation" => Some(Self::Presentation),
            "Spreadsheet" => Some(Self::Spreadsheet),
            "WordProcessor" => Some(Self::WordProcessor),
            "2DGraphics" => Some(Self::Graphics2D),
            "VectorGraphics" => Some(Self::VectorGraphics),
            "RasterGraphics" => Some(Self::RasterGraphics),
            "3DGraphics" => Some(Self::Graphics3D),
            "Scanning" => Some(Self::Scanning),
            "OCR" => Some(Self::OCR),
            "Photography" => Some(Self::Photography),
            "Publishing" => Some(Self::Publishing),
            "Viewer" => Some(Self::Viewer),
            "TextTools" => Some(Self::TextTools),
            "DesktopSettings" => Some(Self::DesktopSettings),
            "HardwareSettings" => Some(Self::HardwareSettings),
            "Printing" => Some(Self::Printing),
            "PackageManager" => Some(Self::PackageManager),
            "Dialup" => Some(Self::Dialup),
            "InstantMessaging" => Some(Self::InstantMessaging),
            "Chat" => Some(Self::Chat),
            "IRCClient" => Some(Self::IRCClient),
            "FileTransfer" => Some(Self::FileTransfer),
            "HamRadio" => Some(Self::HamRadio),
            "News" => Some(Self::News),
            "P2P" => Some(Self::P2P),
            "RemoteAccess" => Some(Self::RemoteAccess),
            "Telephony" => Some(Self::Telephony),
            "TelephonyTools" => Some(Self::TelephonyTools),
            "VideoConference" => Some(Self::VideoConference),
            "WebBrowser" => Some(Self::WebBrowser),
            "WebDevelopment" => Some(Self::WebDevelopment),
            "Midi" => Some(Self::Midi),
            "Mixer" => Some(Self::Mixer),
            "Sequencer" => Some(Self::Sequencer),
            "Tuner" => Some(Self::Tuner),
            "TV" => Some(Self::TV),
            "AudioVideoEditing" => Some(Self::AudioVideoEditing),
            "Player" => Some(Self::Player),
            "Recorder" => Some(Self::Recorder),
            "DiscBurning" => Some(Self::DiscBurning),
            "ActionGame" => Some(Self::ActionGame),
            "AdventureGame" => Some(Self::AdventureGame),
            "ArcadeGame" => Some(Self::ArcadeGame),
            "BoardGame" => Some(Self::BoardGame),
            "BlocksGame" => Some(Self::BlocksGame),
            "CardGame" => Some(Self::CardGame),
            "KidsGame" => Some(Self::KidsGame),
            "LogicGame" => Some(Self::LogicGame),
            "RolePlaying" => Some(Self::RolePlaying),
            "Simulation" => Some(Self::Simulation),
            "SportsGame" => Some(Self::SportsGame),
            "StrategyGame" => Some(Self::StrategyGame),
            "Art" => Some(Self::Art),
            "Construction" => Some(Self::Construction),
            "Music" => Some(Self::Music),
            "Languages" => Some(Self::Languages),
            "Science" => Some(Self::Science),
            "ArtificialIntelligence" => Some(Self::ArtificialIntelligence),
            "Astronomy" => Some(Self::Astronomy),
            "Biology" => Some(Self::Biology),
            "Chemistry" => Some(Self::Chemistry),
            "ComputerScience" => Some(Self::ComputerScience),
            "DataVisualization" => Some(Self::DataVisualization),
            "Economy" => Some(Self::Economy),
            "Electricity" => Some(Self::Electricity),
            "Geography" => Some(Self::Geography),
            "Geology" => Some(Self::Geology),
            "Geoscience" => Some(Self::Geoscience),
            "History" => Some(Self::History),
            "ImageProcessing" => Some(Self::ImageProcessing),
            "Literature" => Some(Self::Literature),
            "Math" => Some(Self::Math),
            "NumericalAnalysis" => Some(Self::NumericalAnalysis),
            "MedicalSoftware" => Some(Self::MedicalSoftware),
            "Physics" => Some(Self::Physics),
            "Robotics" => Some(Self::Robotics),
            "Sports" => Some(Self::Sports),
            "ParallelComputing" => Some(Self::ParallelComputing),
            "Amusement" => Some(Self::Amusement),
            "Archiving" => Some(Self::Archiving),
            "Compression" => Some(Self::Compression),
            "Electronics" => Some(Self::Electronics),
            "Emulator" => Some(Self::Emulator),
            "Engineering" => Some(Self::Engineering),
            "FileTools" => Some(Self::FileTools),
            "FileManager" => Some(Self::FileManager),
            "TerminalEmulator" => Some(Self::TerminalEmulator),
            "Filesystem" => Some(Self::Filesystem),
            "Monitor" => Some(Self::Monitor),
            "Security" => Some(Self::Security),
            "Accessibility" => Some(Self::Accessibility),
            "Calculator" => Some(Self::Calculator),
            "Clock" => Some(Self::Clock),
            "TextEditor" => Some(Self::TextEditor),
            "Documentation" => Some(Self::Documentation),
            "Core" => Some(Self::Core),
            "KDE" => Some(Self::KDE),
            "GNOME" => Some(Self::GNOME),
            "GTK" => Some(Self::GTK),
            "Qt" => Some(Self::Qt),
            "Motif" => Some(Self::Motif),
            "Java" => Some(Self::Java),
            "ConsoleOnly" => Some(Self::ConsoleOnly),
            "Screensaver" => Some(Self::Screensaver),
            "TrayIcon" => Some(Self::TrayIcon),
            "Applet" => Some(Self::Applet),
            "Shell" => Some(Self::Shell),
            _ => None,
        }
    }
}
